### PR TITLE
Set action_dispatch.show_exceptions = false to make testing errors simpler

### PR DESCRIPTION
**Pull request by skryukov**
Targets #139

### CODE REVIEW

**Comment by skryukov** [comment]
@bknoles this PR fixes the failing CI in #139

**Review by BrandonShar — APPROVED** [review]
This is awesome, thank you @skryukov . I had to ask ChatGPT for examples to figure out the different behavior 😄 

Should we just merge this directly to :master: ?

**Comment by skryukov** [comment]
@BrandonShar whatever works for you, I just wanted to help merging #139 😄

**Comment by bknoles** [comment]
Thank you @skryukov ! I haven't gotten back to fixing those specs since I put the PR up the other night.

**Pull request closed without merging**
