### PR TITLE
add railties as the runtime dependency

### PR DESCRIPTION
**Pull request by BenMorganMY**
This releases this gem from depending on the whole Rails suite.

### CODE REVIEW

**Comment by BrandonShar** [comment]
Thanks @BenMorganMY ! Could you explain a bit more about how we would benefit from this change?

Is there anything we lose by no longer requiring rails?

**Comment by BenMorganMY** [comment]
@BrandonShar no, inertia doesn't lose anything from it. Some rails apps actually don't depend on rails itself. For example, we only pull in the rails gems that we need and leave out `actiontext`, `activestorage`, `actioncable`, and so on. Inertia's dependency was very broad and was pulling in gems that it doesn't actually rely on or use.

**Comment by BenMorganMY** [comment]
Hey @BrandonShar, just pinging to see if you're able to get this merged this week and a new release cut?

**Comment by BrandonShar** [comment]
@bknoles what do you think?

I think it probably makes the most sense, my only super minor hedge is what if we do want to depend on one of those rails gems in the future?

**Comment by BenMorganMY** [comment]
@BrandonShar if you need to depend on one of the rails gems in the future, you would want to add it as a dependency in your gemspec.

**Comment by BrandonShar** [comment]
Oh duh... I'm thinking about a future breaking change, but there wouldn't be one at all; the gem still owns the dependency. Thanks I'll get it merged in!

**Review by BrandonShar — APPROVED** [review]

**Comment by BenMorganMY** [comment]
Awesome. Let me know when a new gem is cut.

**Comment by bknoles** [comment]
v3.1.3 hot off the presses!

https://rubygems.org/gems/inertia_rails/versions/3.1.3

I'm chiming in late, but no retroactive objections to merging this. Tests all pass, and I'm happy to have a smaller footprint!

**Pull request merged**
