### PR TITLE
Add inertia_location controller method

### PR DESCRIPTION
**Pull request by BrandonShar**
This adds an `inertia_location` method to keep feature parity with the Laravel version of Inertia.

## Usage

```ruby
def create
   inertia_location index_path
end
```

## Further Reading 

https://github.com/inertiajs/inertia-laravel/pull/154
https://github.com/inertiajs/inertia-laravel/issues/57

### CODE REVIEW

**Review by reinink — APPROVED** [review]
Looks great!￼

**Comment by reinink** [comment]
Once this is merged, it would be *awesome* if you could update the docs for this: https://inertiajs.com/redirects#external-redirects

**Comment by BrandonShar** [comment]
@reinink thanks for the reminder, we'll make sure to update the docs once we go live!

Should be tagged soon, we just want to make sure we understand that test regression. I think it's unrelated, but we needed to set up a local reproduction to be sure.

**Comment by reinink** [comment]
@BrandonShar Thanks! I didn't even notice the failing test with approving. 😅 

It would be great to get this merged in, as this is a pretty handy little feature!

Appreciate all your help. 🙌

**Comment by bknoles** [comment]
https://github.com/rails/rails/pull/28081

found the culprit for the failing test! i'm merging this in and cutting a new release

**Review by bknoles — APPROVED** [review]

**Comment by BrandonShar** [comment]
of course. I figured if it was something like that, but didn't think it was the test itself doing it.

Thanks @bknoles !

**Comment by reinink** [comment]
Thanks for making this happen gents! 🙌

**Pull request merged**
